name: Selenium Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  selenium-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip google-chrome-stable
          pip install selenium webdriver-manager

      - name: Set up XVFB
        run: |
          sudo apt-get install -y xvfb
          Xvfb :99 -screen 0 1920x1080x24 &
        env:
          DISPLAY: ":99"

      - name: Run Selenium Test
        run: |
          python main.py
        env:
          DISPLAY: ":99"

      - name: Upload Debugging Files
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Debugging Files
          path: |
            *.html
            *.png
