name: Selenium Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip libnss3 libxss1 libappindicator1 \
            libindicator7 fonts-liberation libatk1.0-0 libgtk-3-0 libgbm-dev xvfb
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager

    - name: Run Selenium script
      run: |
        export DISPLAY=:99
        Xvfb :99 -screen 0 1920x1080x24 &
        python main.py

    - name: Upload Debugging Files
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: debugging-files
        path: |
          *.html
          *.png
