name: Selenium Tests

on:
  schedule:
    # Runs every 30 minutes
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Chrome dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip \
            libnss3 libxss1 libappindicator1 libindicator7 fonts-liberation \
            libatk1.0-0 libgtk-3-0 libgbm-dev xvfb

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start Xvfb and run Selenium script
      run: |
        export DISPLAY=:99
        Xvfb :99 -screen 0 1920x1080x24 &
        python main.py
      env:
        PYTHONUNBUFFERED: 1  # Sorgt dafür, dass Logs direkt in die Ausgabe geschrieben werden

    - name: Save artifacts for debugging
      if: failure()  # Läuft nur, wenn ein Fehler auftritt
      uses: actions/upload-artifact@v2
      with:
        name: selenium-debug
        path: |
          debug_screenshot.png
          *.log
